### ISSUE TITLE
my project does not compile because of google-play-services-custom.jar and CloudPush

### ISSUE THREAD

**Issue by annakozy2011** [SeanChristopherConway/titanium-google-geofence#1]
It seems to be because you have added google-play-services-custom.jar

Besides it, I use CloudPush, so it brings in google-play-services-base.jar and google-play-services-gcm.jar. 

Any ideas how to make it compatible?

Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/ItemListIntents;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/NoteIntents;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/ReserveIntents;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/SearchIntents;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEvent;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEventsRequest;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEventsResponse;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/Auth$1;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/Auth$2;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :   at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR] :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[ERROR] :   at com.android.dx.command.dexer.Main.run(Main.java:277)
[ERROR] :   at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR] :   at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :   at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR] :   ... 4 more

**Comment by annakozy2011** [comment]
For the time being I compared google-play-services-base.jar in CloudPush and google-play-services-custom.jar in this module, and the custom seems to be a superset of the base (includes location). 

So I suppose if I throw out google-play-services-base.jar from CloudPush it should work. But I don´t know for sure, plus it probably should not be this tricky.

**Comment by SeanChristopherConway** [comment]
@annakozy2011 Hello. Yes, exactly. Because Appcelerator does not use proguard so you must have all instances of any one class in an identically named jar file. You cannot simply add a full version of the goole play services jar because they do not optimize it by only using the necessary classses, and try to load all---so you get a memory crash(once again solved years ago in Android Studio). Thus, add this jar to every place you use the google play services jar, and if you need other libraries then make another jar just with the other classes, for example google-play-services-gcm.jar.

**Comment by SeanChristopherConway** [comment]
I use http://www.zipeg.com/ to view jars. When I open them up I simply do this: 
(1) Rename the jar file to a zip file.
(2) Take out the classes/split up the classes into separate folders as desired
(3) Zip the desired class folders.
(4) Remove some undesirables and rename zip folder if you did not already, eg. zip -d com.zip __MACOSX/*;mv com.zip google-play-services.zip;zip -d google-play-services.zip */.DS_Store
(5) Rename to .jar 

So you can download the newest google play and split out the classes you need, then you must have the same copies in every instance where you need all those classes.

**Comment by SeanChristopherConway** [comment]
For example, I am using the following jar in combination with my custom one with ti.cloudpush, as it needs more classes than the ones in my custom jar. https://drive.google.com/open?id=0BxDo-Bwhg2pmeks3Vm9vazY4emc
